### ISSUE TITLE
Possible to manage only specific components?

### ISSUE THREAD

**Issue by timrburnham** [IBM/ansible-role-infosvr#15]
I need to install only the 11.5 client on a number of Windows machines. The way the setup_vars task is written, it appears to require facts across all tiers, even with all the other `ibm_infosvr_features` disabled. Is there any way to avoid that requirement and manage only certain components?

**Comment by cmgrote** [comment]
Hi @timrburnham -- good question, it's true I haven't tried to use them for this use case. It could be as easy as putting a few more `when: ('ibm-information-server-clients' not in group_names)` conditionals against those items in the `setup_vars` tasks that are not used for client installation anyway. Is that something you'd be comfortable trying, and if successful submitting a PR for?

I suspect it would need to be added to all tasks that do not already have a `when: ` conditional, _except_ the `default any missing features to disabled` task (that one should remain without any conditionals).

I don't really have any Windows environments around anymore to easily test on my side...
