### ISSUE TITLE
WARNING: Ensure that the operating system has at least 8 GB memor

### ISSUE THREAD

**Issue by Ramnikov** [IBM/ansible-role-infosvr#28]
When I running the role on CentOS 7 i get the bellow error:

**WARNING: Ensure that the operating system has at least 8 GB memory. Found 7.638 GB memory. If you continue the install, The installation program might not complete successfully. This system should not be used for Production until memory has been added**.

As a result DB2 installation fails.
The same happens with WebSphere even if I set the memory to 16GB.

**_2020-10-03T13:38:09.708, SEVERE: com.ibm.is.install.engine.requirement.RequirementCheckingVistor  WARNING: Ensure that the operating system has at least 8 GB memory.  Found 7.638 GB memory. If you continue the install, The installation program might not complete successfully. This system should not be used for Production until memory has been added.
2020-10-03T13:38:09.708, SEVERE: com.ibm.is.install.Installer^M
com.ibm.is.install.exception.RequirementsNotMetException: CDIIN4228E: Some of the installation requirement checks failed.  Specific failure information will be found in preceding error messages.
        at com.ibm.is.install.engine.requirement.RequirementCheckingVistor.visitRequirement(RequirementCheckingVistor.java:47)
        at com.ibm.is.install.engine.requirement.RequirementsReport.accept(RequirementsReport.java:50)
        at com.ibm.is.install.AbstractInstaller.checkRequirements(AbstractInstaller.java:887)
        at com.ibm.is.install.AbstractInstaller.recoverAndExecutePlan(AbstractInstaller.java:691)
        at com.ibm.is.install.AbstractInstaller.execute(AbstractInstaller.java:414)
        at com.ibm.is.install.Installer.main(Installer.java:107)_**

**Comment by cmgrote** [comment]
Hi @Ramnikov -- in general you can have the system ignore these check failures by setting the following override in the vars (`defaults/main.yml` or your own override file):

```
ibm_infosvr_force:          # Set to true to force installs (ignore errors or warnings)
  repo: True
  domain: True
  engine: False
  client: False
  patch: True
```

This will override any errors or warnings for installing the repository tier (DB2), the domain tier (WAS) and any patches. If you want to do the same for either the engine or client tiers, just swap those to `True` as well.

**Comment by Ramnikov** [comment]
Many Thanks. This solved the issue.
I would suggest in your Vagrant file to add the following:


Vagrant.configure(2) do |config|

  config.vm.define "infosvr" do |infosvr|
    infosvr.vm.box = "centos/7"
    infosvr.vm.network "private_network", ip: "192.168.27.12"
    **infosvr.vm.network "forwarded_port", guest: 9043, host: 9043, auto_correct: true   
    infosvr.vm.network "forwarded_port", guest: 9446, host: 9446, auto_correct: true**  
    infosvr.vm.hostname = "infosvr.vagrant.ibm.com"
    infosvr.vm.synced_folder ".", "/vagrant", disabled: true
    infosvr.vm.provider "virtualbox" do |vb|
      vb.gui = false
      **vb.memory = 16384**
      vb.cpus = 4
    end
  end

end

**Comment by cmgrote** [comment]
Sounds reasonable (I haven't used the Vagrant piece in a very long time)...  would you care to submit a PR with the changes?

**Comment by Ramnikov** [comment]
isssue fixed
